apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks_rest-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks_rest
    template:
      metadata:
        labels:
          app: tasks_rest
      spec:
        containers:
          - name: tasks_rest
            image: tasks_rest:9547b34